/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iuran;

import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Dafimz
 */
public class UI_PBI extends javax.swing.JFrame {
    static Connection conn;
    static Statement stmt;
    static ResultSet rs;
    static String nmr,nik, fsks, sts, tb, nokk, nma, almt, ttl, fileName, filecontent; 

    public static String ShowData(String where){
       String sql = "SELECT KARTU.nomor_kartu, KARTU.nik, KARTU.faskes, KARTU.status, KARTU.terakhir_bayar, data_diri.nomor_kk,data_diri.nama, data_diri.alamat, data_diri.ttl FROM kartu INNER JOIN data_diri ON kartu.nik = data_diri.nik WHERE kartu.nomor_kartu='"+where+"'";
       return sql;
    }
    /**
     * Creates new form UI_PBI
     */
    public UI_PBI() {
        initComponents();
    }
 public void cetakStruk(String fileName, String fileContent){
        try {
            FileWriter fileWriter = new FileWriter(fileName);
            fileWriter.write(fileContent);
            fileWriter.close();
            System.out.println("File sudah ditulis ulang!");
        }catch (IOException e) {
            System.out.println("Terjadi kesalahan karena: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Pengecekan Peserta PBI");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Masukan Nomor Kartu BPJS : ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 20));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 170, -1));

        jButton1.setText("Cek");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 90, -1));

        jLabel3.setText("Keterangan : Untuk peserta PBI pembayaran ditanggung pemerintah");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 400, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
        Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/bpjs","root","");
            stmt = conn.createStatement();
            
            Scanner input1=new Scanner(System.in);
            String b = jTextField1.getText();
            rs= stmt.executeQuery(ShowData(b));
            
            while(rs.next()){
                nmr = rs.getString("nomor_kartu");
                nik = rs.getString("nik");
                fsks = rs.getString("faskes");
                sts = rs.getString("status");
                tb = rs.getString("terakhir_bayar");
                nokk = rs.getString("nomor_kk");
                nma = rs.getString("nama");
                almt = rs.getString("alamat");
                ttl = rs.getString("ttl");
                
            }
            PBI d =new PBI(nmr, nik, fsks, sts, tb, nokk, nma, almt, ttl);
            System.out.println(nmr);
            if ("PBI".equals(sts)){
                JOptionPane.showMessageDialog(null, "Anda adalah anggota PBI");
                int v=0;
                rs=stmt.executeQuery("SELECT * FROM data_diri WHERE nomor_kk = '"+nokk+"'");
                while(rs.next()){
                    v++;
                }
                fileName="src/PBI_"+nmr+".txt";
                filecontent=
                        "===Status Anggota PBI===\n"
                        +"Nomor    : " +nmr+"\n"
                        +"NIK      : " +nik+"\n"
                        +"Nama     : " +nma+"\n"
                        +"Alamat   : " +almt+"\n"
                        +"Faskes   : " +fsks+"\n"
                        +"Status   : " +sts+"\n"
                        +"Keluarga : " +v+" Orang\n"; 
                cetakStruk(fileName,filecontent);
                JOptionPane.showMessageDialog(null, "Pengecekan Anggota Sukses. Informasi anda telah diproses");
            }
            else{
                 JOptionPane.showMessageDialog(null, "Nomor yang anda masukan salah atau anda bukan anggota PBI!");
            }
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(UI_PBI.class.getName()).log(Level.SEVERE, null, ex);
        }  
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_PBI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_PBI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_PBI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_PBI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI_PBI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
